#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the UPS
# goes on batteries.
# We send an email message to root to notify him.
#
SYSADMIN=user@yahoo.com
APCUPSD_MAIL="/bin/mail"

HOSTNAME=`hostname`
MSG="$HOSTNAME initiated Shutdown Sequence"
#
(
   echo "Subject: $MSG"
   echo " "
   echo "$MSG"
   echo " "
   /sbin/apcaccess status 
) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN


nowtime=`date +'%H:%M:%S'`
apc=`apcaccess status |grep -E '(^BCHARGE)'|awk -F' :' '{print $2}'`
message="The host has initiated shutdown sequence $nowtime (minatoku, tokyo) BCHARGE:$apc #teiden @tinbotu"
/home/kuma/bin/teidensita/post.rb /home/kuma/bin/teidensita/token "$message"
/home/kuma/bin/boxcar.rb "$message"

exit 0
